name: cifar10_imb01_stage1_mixup_vgg
print_freq: 40
workers: 1
log_dir: 'logs'
model_dir: 'ckps'

# dataset & model setting
dataset: 'cifar10'
data_path: './data/cifar10'
num_classes: 10
imb_factor: 0.1
backbone: 'vgg16'
resume: ''
head_class_idx:
  - 0
  - 3
med_class_idx:
  - 3
  - 7
tail_class_idx:
  - 7
  - 10


# distributed training
deterministic: False
distributed: False
gpu: 0
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
dist_backend: 'nccl'
multiprocessing_distributed: False



# Train
mode: 'stage1'
lr: 0.1
batch_size: 128
weight_decay: 2e-4
num_epochs: 200
momentum: 0.9
cos: False
mixup: True
alpha: 1.0
gamma: 1.0




